AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: >
  ec2-idle

  Sample SAM Template for ec2-idle

Resources:
  #  EC2IdleManagerPolicy:
  #    Type: AWS::IAM::Policy
  #    Properties:
  #      PolicyName: EC2IdleManager
  #      PolicyDocument:
  #        Version: "2012-10-17"
  #        Statement:
  #          - Effect: Allow
  #            Action: ["ec2:DescribeInstances", "ec2:StopInstances"]
  #            Resource: "*" #InstanceProfile:

  TriggerFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: ec2_idle/
      Handler: trigger.trigger_handler
      Timeout: 180
      Tags:
        Project: "platform"
      Policies:
        - Statement:
            - Sid: EC2IdleManagerTriggerLambda
              Effect: Allow
              Action:
                - lambda:InvokeFunction
              Resource: !GetAtt WorkerFunction.Arn
        - Statement:
            - Sid: EC2IdleManagerTriggerEC2
              Effect: Allow
              Action:
                - ec2:DescribeInstances
              Resource: "*"
      Runtime: python3.8
      VpcConfig:
        SecurityGroupIds:
          - sg-8b5c50ee
        SubnetIds:
          - subnet-6577a03c
          - subnet-a752c0c2
          - subnet-325eee45
      Events:
        IdleEC2Shutdown:
          Type: Schedule
          Properties:
            Schedule: rate(1 hour)
  WorkerFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: ec2_idle/
      Handler: worker.worker_handler
      Timeout: 20
      Tags:
        Project: "platform"
      Policies:
        - Statement:
            - Sid: EC2IdleManagerWorkerEC2
              Effect: Allow
              Action:
                - ec2:StopInstances
              Resource: "*"
            - Sid: EC2IdleManagerWorkerS3
              Effect: Allow
              Action:
                - s3:GetObject
              Resource: "arn:aws:s3:::fdotech/*"
      Runtime: python3.8
      VpcConfig:
        SecurityGroupIds:
          - sg-8b5c50ee
        SubnetIds:
          - subnet-6577a03c
          - subnet-a752c0c2
          - subnet-325eee45
